name: capstone
channels:
  - conda-forge
dependencies:
  - python=3.11
  - duckdb
  - pandas
  - plotly
  - polars
  - matplotlib
  - ipykernel
  - nbformat
  - notebook
  - seaborn
  - yfinance
  - dask
  - pandas-datareader
  - nltk
  - gensim
  - scikit-learn
  - gdown
  - scipy
  - hmmlearn
  - pgmpy
  - pip
  - pyarrow
  - nbformat>=4.2.0
  - pip:
      - -r requirements.txt