project:
  type: website

website:
  title: "AdaptiveSats"
  description: "Exploring data-driven Bitcoin accumulation strategies."
  site-url: "https://<USERNAME>.github.io/AdaptiveSats"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: index.qmd      
      - icon: github
        href: https://github.com/ShrutiSasi/AdaptiveSats
format:
  html:
    theme: cosmo
    css: styles.css
